project_name: terraform-provider-cloudstack

builds:
  - id: binary
    binary: '{{ .ProjectName }}_v{{ .Version }}'
    dir: .
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
    - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.BuildUser={{.Env.USER}}
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
    goos:
      # - freebsd
      # - openbsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      # - '386'
      # - arm
      # - arm64
    # ignore:
    #   - goos: darwin
    #     goarch: '386'
    #   - goos: openbsd
    #     goarch: arm
    #   - goos: openbsd
    #     goarch: arm64
    #   - goos: windows
    #     goarch: arm64

archives:
  # - id: archives
  #   builds:
  #     - binary
  #   format: "tar.gz"
  #   name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  #   wrap_in_directory: true
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  extra_files:
  - glob: 'terraform-registry-manifest.json'
    name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  github:
    owner: orange-cloudfoundry
    name: terraform-provider-cloudstack
  extra_files:
  - glob: 'terraform-registry-manifest.json'
    name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
